services:
  - type: web
    name: teikyo-webapp
    runtime: node
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true

